export const newsData = [
  {
    id: 1,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
  {
    id: 2,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
  {
    id: 3,
    title: "Following the delay of next Dragon Quest, producer Yu Miyake has reportedly been fired",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
  {
    id: 4,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
  {
    id: 5,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
  {
    id: 6,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
  {
    id: 7,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
  {
    id: 8,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
  {
    id: 9,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
  },
];
