export const reviewsData = [
  {
    id: 1,
    img: "/gta.jpg",
    title: "Grand Theft Auto V: Premium Online Edition",
    author: "userName1",
    rating: 3,
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam culpa deserunt facere impedit ipsa iure, molestiae nam neque nobis numquam pariatur perferendis quas quidem rem soluta tempora unde ut! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam culpa deserunt facere impedit ipsa iure, molestiae nam neque nobis numquam pariatur perferendis quas quidem rem soluta tempora unde ut!",
  },
  {
    id: 2,
    img: "/rdr.jpg",
    title: "Red Dead Redemption 2",
    author: "userName1",
    rating: 4,
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam culpa deserunt facere impedit ipsa iure, molestiae nam neque nobis numquam pariatur perferendis quas quidem rem soluta tempora unde ut!",
  },
  {
    id: 3,
    img: "/punk.jpg",
    title: "Cyberpunk 2077: Ultimate Edition",
    author: "userName2",
    rating: 4,
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam culpa deserunt facere impedit ipsa iure, molestiae nam neque nobis numquam pariatur perferendis quas quidem rem soluta tempora unde ut!",
  },
  {
    id: 4,
    img: "/gta.jpg",
    title: "Grand Theft Auto V: Premium Online Edition",
    author: "userName1",
    rating: 3,
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam culpa deserunt facere impedit ipsa iure, molestiae nam neque nobis numquam pariatur perferendis quas quidem rem soluta tempora unde ut! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam culpa deserunt facere impedit ipsa iure, molestiae nam neque nobis numquam pariatur perferendis quas quidem rem soluta tempora unde ut!",
  },
  {
    id: 5,
    img: "/rdr.jpg",
    title: "Red Dead Redemption 2",
    author: "userName1",
    rating: 4,
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam culpa deserunt facere impedit ipsa iure, molestiae nam neque nobis numquam pariatur perferendis quas quidem rem soluta tempora unde ut!",
  },
  {
    id: 6,
    img: "/punk.jpg",
    title: "Cyberpunk 2077: Ultimate Edition",
    author: "userName2",
    rating: 4,
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam culpa deserunt facere impedit ipsa iure, molestiae nam neque nobis numquam pariatur perferendis quas quidem rem soluta tempora unde ut!",
  },
];
